### PR TITLE
Add click attribute on Notification

### PR DESCRIPTION
**Pull request by sergiocosus**
Added a way to listen click event on a Notification

### CODE REVIEW

**Comment by flauc** [comment]
Can you just adjust the code to pass linting: 

(quotemark) src/notification.type.ts[1, 30]: " should be '

**Comment by flauc** [comment]
Thank you for the PR 👍

**Comment by sergiocosus** [comment]
Hi! @flauc 
The last commit seems to be fine, Do I need to do something more?

Thanks!

**Comment by flauc** [comment]
No you don't I'm sorry i missed that one.

**Comment by flauc** [comment]
I'll publish this to npm later today. Thanks again 👍

**Comment by michalstepien** [comment]
(click)="onClick($event)" should be

**Pull request merged**
