### PR TITLE
Allow AoT building

### PR DESCRIPTION
**Pull request by jlberrocal**
Using [this library](https://www.npmjs.com/package/angular-library-builder) is very easy to create the AoT ready compilation of a library, please give it a check, because this feature is very important

### CODE REVIEW

**Comment by tilowestermann** [comment]
I agree that AoT is important, especially if you want to build with angular-cli in production mode.

**Comment by flauc** [comment]
Thanks , hope it works. I have had some trouble implementing it in the past 👍

**Comment by jlberrocal** [comment]
@flauc any updates?

**Comment by victornoel** [comment]
@flauc any reason why this was reverted on master?

**Comment by flauc** [comment]
Yes, because it doesn't work.

**Comment by victornoel** [comment]
@flauc do you know why or what is the problem? would be cool to have

**Comment by flauc** [comment]
It was 'nclb' is undefined or something along those lines.

But AoT is working fine for me with the current version. This is a production application using it:

https://jaspero.co/resources/projects/ng-notifications

**Comment by victornoel** [comment]
@flauc you need to add `angular-library-builder` it to the `devDependencies` simply…

I was surprised also by this PR, because I do use it in an AOT application and it seems to work as desired.

@jlberrocal could you clarify the situation for us? are you sure it's not already working as desired?

**Comment by flauc** [comment]
@victornoel after adding the `angular-library-builder` the build compiles, but it no longer worked for me in AoT in my projects. So I assumed it doesn't work in most cases.

**Comment by victornoel** [comment]
hm ok, well, I guess it would be worth clarifying…

I see that in the PR, it puts the simple-notification module but not the push-notification module, so I suppose the PR was actually unfinished.

I feel like angular-library-builder is useful to produce optimized artefacts to be distributed, but has not so much to do with AOT in the end.

I hope @jlberrocal will give us some feedbacks on that :)

**Comment by jlberrocal** [comment]
@victornoel currently if i install the NPM version and i try to compile with AoT i get the error reported here, so i decided to make the fork and it worked (for me), so currently i'm using my own version of this repo, however i haven't tested the last version relased by @flauc 

@victornoel i guess that you are right i just "exported" the simple-notifications-module mainly because that was the module that i was needing, but that doesn't mean that my PR is wrong at all it was just to give an idea to @flauc about how to proceed with this feature

Anyway @flauc are you totally sure that this will work as SystemJS as well for webpack/ng-cli? because i'm facing the error on Webpack

**Comment by aliyeysides** [comment]
I'm facing this issue as well. I'm using cli and it works without `ng build --aot`. Any updates?

**Pull request merged**
