### PR TITLE
fixed codelyzer path

### PR DESCRIPTION
**Pull request by NielsVerheijen**
Seeing as codelyzer and angular2-notifications are in the same dir, this should do the trick.

### CODE REVIEW

**Comment by NielsVerheijen** [comment]
#224

**Comment by flauc** [comment]
Yes, I think you're right. Thank you 👍

**Comment by NielsVerheijen** [comment]
Apparently it doesn't really agree with the Travis CI builder..

**Comment by flauc** [comment]
Meh the build is a bit on and off sometimes it fails for reasons I can't explain :)

**Pull request merged**
