### PR TITLE
"fixed" deprecation warning ("Template parse warnings")

### PR DESCRIPTION
**Pull request by f4bio**
it just really bugged me :D 
merge if you like and/or not already "fixed" it yourself

### CODE REVIEW

**Comment by flauc** [comment]
Thank you :+1:

**Comment by samvaughton** [comment]
Any chance of a minor release soon? Just so I can upgrade to pull in these changes? Thanks

**Comment by flauc** [comment]
I was planing on updating to rc-1 later today.

**Comment by samvaughton** [comment]
Awesome!

**Comment by f4bio** [comment]
> I was planing on updating to rc-1 later today.

nice! I've started to do so myself a couple minutes ago.
Let me know if you need help, don't have enough time or anything else - always happy to help!

**Comment by flauc** [comment]
Thank you so much, 

I'm always in some kind of a rush so please feel free to help out when ever you're up for it :+1:

**Pull request merged**
