### PR TITLE
Angular 8 compatibility, and move from gulp to ng-cli

### PR DESCRIPTION
**Pull request by youkouleley**
Gulp used to be the best way to build an Angular library, now `ng-cli` provides everything with better integration.
The PR also provides Angular 9 compatibility, even if not released yet (tested only on Angular 9)

For me this is still a work in progress, it needs extensive tests, documentation update, etc... and it should not be released before Angular 9, but I don't know how to propose a PR on a new branch of the original repo (not master)

### CODE REVIEW

**Comment by youkouleley** [comment]
@romontei if the plan is to release a Angular 8 compatible version, then I think we should downgrade the `package.json` dependencies to Angular 8 instead of `~9.0.0-next.12` because it's still unstable. It should probably work out-of-the-box.

**Comment by romontei** [comment]
I guess you're right, Angular 8 compatibility is already a big step forward !

**Comment by youkouleley** [comment]
As discussed, it's too early for Angular 9, so I downgraded the PR to Angular 8. I also added the `peerDependencies` that were missing. Review it when you want.

**Comment by flauc** [comment]
thank you  @youkouleley and @romontei  I'll build it locally and test as soon as possible.

**Comment by youkouleley** [comment]
One word about the lint configuration changes: I had an error message complaining about some inexistent rules, so I introduced a more "modern" lint configuration which didn't change much to the codebase, except that it removed the `public` accessors.
When searching the web about this, I found this article https://medium.com/@martin_hotell/10-typescript-pro-tips-patterns-with-or-without-react-5799488d6680 which states it's better to remove `public` accessors as it makes the TypeScript code closer to the generated JavaScript.

**Comment by romontei** [comment]
Hi ! Any update @flauc ?

**Comment by youkouleley** [comment]
What can I do to accelerate the process?

**Comment by youkouleley** [comment]
@flauc we need some feedback. This project needs the latest Angular version compatibility, otherwise it won't be viable anymore. I am contributing as much as I can, now will you be able to review this in a near future? You could allow some big contributors to accept pull requests if you have zero time to spend on it.

**Comment by flauc** [comment]
Hey @youkouleley I'm sorry for the delays I really am. Would you like to get involved as someone who would accept and check PRs? I'm merging this one in.

**Comment by youkouleley** [comment]
Oh I didn't expect an instant merge, just be careful about the version number that is set to `1.0.0` and needs to be updated for future release.

If you want me to, I could get involved in pull requests and spend some of my time on it. I'm using this library on multiple projects, so I'd definitely be happy to make it live.

**Comment by flauc** [comment]
That would be extremely helpful I have close to 0 time now a days. I've added you as a collaborator.

**Comment by youkouleley** [comment]
Ok thanks for inviting me, I'll fix the TravisCI build tonight

**Comment by youkouleley** [comment]
Build fixed and version number changed to 3.0.0, I also introduced two breaking changes:
- Change `onCreate` to `create`
- Change `onDestroy` to `destroy`

This is to comply with angular styleguide for events naming.

**Comment by vojtechruz** [comment]
Thanks a lot guys, appreciate that :)

**Comment by stalkert** [comment]
Hi. When these changes will appear in npm repository? Now, still available only 2.0.0 version.

**Comment by vespertilian** [comment]
@stalkert so the package is working for you when you install it via GitHub? I get an error when I build it and link it. 

```
AppComponent.ngfactory.js? [sm]:1 ERROR NullInjectorError: StaticInjectorError(AppModule)[NotificationComponent -> ViewRef]: 
  StaticInjectorError(Platform: core)[NotificationComponent -> ViewRef]: 
    NullInjectorError: No provider for ViewRef!
```

**Comment by stalkert** [comment]
@vespertilian   I have installed but unfortunately, it does not work ( npm install git+https://git@github.com/flauc/angular2-notifications.git#master). It just helped fix migration issue (from Agular 7 to 8). After that, I made rollback to v2.0.0. I have checked my app. It is still working.

**Comment by vespertilian** [comment]
@stalkert ok, good to know. I changed the viewRef back to changeDetectorRef and that seemed to work for me in the Angular 8 3.0 branch.

@youkouleley why did you change CDR to viewRef? Is this working for you in Angular 8?

**Comment by youkouleley** [comment]
The reason is that the `destroyed` property only exists on `ViewRef` in Angular 8.
I've provided a fix, it works for me, please test it and tell us if this is ready for a release

**Comment by GerdVW** [comment]
Hi guys, I'm also looking for an Angular 8 compatible version of the angular2-notifications. 
I've built the latest commit from master wih the changeDetectorRef injection, but I still have the same error as with the viewRef: 

```
AppComponent.html:3 ERROR NullInjectorError: StaticInjectorError(AppModule)[NotificationComponent -> ChangeDetectorRef]: 
  StaticInjectorError(Platform: core)[NotificationComponent -> ChangeDetectorRef]: 
    NullInjectorError: No provider for ChangeDetectorRef!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (http://localhost:4200/vendor.js:99358:25)
```

As far as I know, I don't need any additional code to inject the ChangeDetectorRef?

**Comment by youkouleley** [comment]
Do you build with `npm run build`?

I'm on holidays with no access to a computer, I'll have time to spend on the problem in january. Any investigation/pull request is welcome if you want to help me.

**Comment by youkouleley** [comment]
@GerdVW please detail how to reproduce your problem. I have no problems with a new Angular `8.2.14` project.
Also, if someone else could test this, and give some feedback, it would be nice.

**Comment by GerdVW** [comment]
Hi @youkouleley , my appologies for my late response. 
I just created a clean new Angular 8 project (8.3.22) to test this.

- I added the NPM dependency to a locally built version ("npm run build" on the latest version (commit 5a2729610c43d7dd08bc7240b0cd97954919e586)).

- I registered SimpleNotificationsModule.forRoot() in the app.module.ts file
- I inject/use the NotificationsService in the AppComponent to display an alert when a button is clicked.
- I double-checked that I'm using the right library

When I launch, I still get "NullInjectorError: "StaticInjectorError(AppModule)[NotificationComponent -> ChangeDetectorRef]: 
  StaticInjectorError(Platform: core)[NotificationComponent -> ChangeDetectorRef]: 
    NullInjectorError: No provider for ChangeDetectorRef!""

I pushed the app here: https://github.com/GerdVW/test-app.

I probably missed something/somewhere but I don't see it...?

**Comment by GerdVW** [comment]
Not sure if it helps, but I can easily inject the ChangeDetectorRef in the AppComponent... but once I add the <simple-notifications> component (without options or event-bindings), I get the error.

**Comment by GerdVW** [comment]
@youkouleley, I finally found out what the issue was. Because I've built the project locally, and referred to it through a file-reference in my package.json, NPM created a symlink in my node_modules folder to point to the freshly built library. I'm not sure why, but it seems that this symlink is needed to actually use Angular's dependency-injection.
By configuring the "preserveSymlinks": true," option in my own project's angular.json (architect -> build -> options), the symlink is preserved... and the dependencies are injected as expected...

Library looks good at first sight. If I have some spare time, I can test a bit more thorough. 

It would be nice if some other users would also test the new version, but are you planning on pushing this version to NPM repo any time soon?

**Comment by youkouleley** [comment]
I'd like to but @flauc didn't allow me to publish yet

**Comment by youkouleley** [comment]
I've finally published it Yesterday as V3.0.0

**Comment by GerdVW** [comment]
Great! Many thanks!

**Comment by romontei** [comment]
Thanks guys ! Nice work !

**Pull request merged**
