### PR TITLE
refactoring to remove implicit any type to notification service and n…

### PR DESCRIPTION
**Pull request by netstart**

### CODE REVIEW

**Comment by netstart** [comment]
I think the NotificationEvent.id is never defined, so,  the case 'clean' in simple-notifications.component.ngOnInit is not used
```
  case 'clean':
            this.cleanSingle(item.id);
            break;

```

**Comment by netstart** [comment]
Sorry,  don´t need readme.md

Is only to me :D


What do you think about angular cli. I think adding support for angular cli, to execute testes.

Like this...

```
import {MaxCharacterePipe} from '../max-charactere.pipe';

  describe('common/components/notification/test/max-charactere.pipe.spec.ts', () => {
    let pipe: MaxCharacterePipe;

    beforeEach(() => {
      pipe = new MaxCharacterePipe();
    });

    it('Has characteres allowed', () => {
      expect(pipe.transform('abc', 3)).toEqual('abc');
    });


    it('Has characteres not allowed (slice)', () => {
      expect(pipe.transform('abc', 2)).toEqual('ab');
    });

  });
```

```
import {inject, TestBed} from '@angular/core/testing';
import {NotificationsService} from '../notifications.service';
import {NotificationEvent} from '../notification-event.type';
import {Notification} from '../notification.type';
import {Icons, defaultIcons} from '../icons';


  describe('common/components/notification/test/notifications.service.spec.ts', () => {

    beforeEach(() => {
      TestBed.configureTestingModule({
        declarations: [],
        providers: [NotificationsService],
      });
    });

    let icons: Icons = defaultIcons;

    it('can instantiate service when inject service',
      inject([NotificationsService], (service: NotificationsService) => {
        expect(service instanceof NotificationsService).toBeTruthy();
      })
    );

    it('override = null, need notify with command equal set and override id',
      inject([NotificationsService], (service: NotificationsService) => {

        let notificationEvent: NotificationEvent = null;
        service.getChangeEmitter().subscribe(item => notificationEvent = item);

        let notification: Notification = {
          id: '0', type: '', icon: '', title: '',
          content: '', override: null, html: 'any', state: '',
          createdOn: new Date(), destroyedOn: new Date()
        };

        service.set(notification, true);

        expect(notificationEvent.command).toBe('set');
        expect(notificationEvent.id !== '0').toBeTruthy();
      })
    );

    it('override valid, notify with command set and define id = override.id ',
      inject([NotificationsService], (service: NotificationsService) => {

        let notificationEvent: NotificationEvent = null;
        service.getChangeEmitter().subscribe(item => notificationEvent = item);

        let notificationOverride: Notification = {
          id: '2', type: '', icon: '', title: '',
          content: '', override: null, html: 'any', state: '',
          createdOn: new Date(), destroyedOn: null
        };

        let notification: Notification = {
          id: '0', type: '', icon: '', title: '',
          content: '', override: notificationOverride, html: 'any', state: '',
          createdOn: new Date(), destroyedOn: null
        };

        service.set(notification, true);

        expect(notificationEvent.command).toBe('set');
        expect(notificationEvent.notification.id).toBe('2');
      })
    );

    it('call sucess method',
      inject([NotificationsService], (service: NotificationsService) => {
        let notificationEvent: NotificationEvent = null;
        service.getChangeEmitter().subscribe(item => notificationEvent = item);

        let notification: Notification = service.success('Window title', 'Content message');

        expect(notificationEvent.command).toBe('set');
        expect(notificationEvent.id).toBeUndefined();

        expect(notification.id !== undefined).toBeTruthy();
        expect(notification.type).toBe('success');
        expect(notification.icon).toBe(icons.success);

        expect(notification.title).toBe('Window title');
        expect(notification.content).toBe('Content message');
        expect(notification.override).toBeUndefined();
        expect(notification.html).toBeUndefined();
        expect(notification.state).toBeUndefined();
        expect(notification.createdOn).toBeUndefined();
        expect(notification.destroyedOn).toBeUndefined();
      })
    );//end test success

    it('call sucess method override',
      inject([NotificationsService], (service: NotificationsService) => {
        let notificationEvent: NotificationEvent = null;
        service.getChangeEmitter().subscribe(item => notificationEvent = item);

        let notification: Notification = service.success('Window title', 'content message');
        let notificationOver: Notification = service.success('Window title override', 'content message overrided', notification);

        expect(notificationOver.type).toBe('success');
        expect(notificationOver.icon).toBe(icons.success);
        expect(notificationOver.title).toBe('Window title override');
        expect(notificationOver.content).toBe('content message overrided');

        expect(notificationEvent.command).toBe('set');
        expect(notificationEvent.id).toBeUndefined();

        expect(notification.id).toBe(notificationOver.id);//deve ser  o mesmo id
        expect(notification.type).toBe('success');
        expect(notification.icon).toBe(icons.success);

        expect(notification.title).toBe('Window title');
        expect(notification.content).toBe('content message');
        expect(notification.override).toBeUndefined();
        expect(notification.html).toBeUndefined();
        expect(notification.state).toBeUndefined();
        expect(notification.createdOn).toBeUndefined();
        expect(notification.destroyedOn).toBeUndefined();


      })
    );//end test success


    it('call error method',
      inject([NotificationsService], (service: NotificationsService) => {
        let notificationEvent: NotificationEvent = null;
        service.getChangeEmitter().subscribe(item => notificationEvent = item);

        let notification: Notification = service.error('Window title', 'Content message');

        expect(notificationEvent.command).toBe('set');

        expect(notification.id !== undefined).toBeTruthy();
        expect(notification.type).toBe('error');
        expect(notification.icon).toBe(icons.error);

        expect(notification.title).toBe('Window title');
        expect(notification.content).toBe('Content message');
        expect(notification.override).toBeUndefined();
        expect(notification.html).toBeUndefined();
        expect(notification.state).toBeUndefined();
        expect(notification.createdOn).toBeUndefined();
        expect(notification.destroyedOn).toBeUndefined();
      })
    );//test error


    it('call alert method',
      inject([NotificationsService], (service: NotificationsService) => {
        let notificationEvent: NotificationEvent = null;
        service.getChangeEmitter().subscribe(item => notificationEvent = item);

        let notification: Notification = service.alert('Window title', 'Content message');

        expect(notificationEvent.command).toBe('set');

        expect(notification.id !== undefined).toBeTruthy();
        expect(notification.type).toBe('alert');
        expect(notification.icon).toBe(icons.alert);

        expect(notification.title).toBe('Window title');
        expect(notification.content).toBe('Content message');
        expect(notification.override).toBeUndefined();
        expect(notification.html).toBeUndefined();
        expect(notification.state).toBeUndefined();
        expect(notification.createdOn).toBeUndefined();
        expect(notification.destroyedOn).toBeUndefined();
      })
    ); //test alert


    it('call alert info',
      inject([NotificationsService], (service: NotificationsService) => {
        let notificationEvent: NotificationEvent = null;
        service.getChangeEmitter().subscribe(item => notificationEvent = item);

        let notification: Notification = service.info('Window title', 'Content message');

        expect(notificationEvent.command).toBe('set');

        expect(notification.id !== undefined).toBeTruthy();
        expect(notification.type).toBe('info');
        expect(notification.icon).toBe(icons.info);

        expect(notification.title).toBe('Window title');
        expect(notification.content).toBe('Content message');
        expect(notification.override).toBeUndefined();
        expect(notification.html).toBeUndefined();
        expect(notification.state).toBeUndefined();
        expect(notification.createdOn).toBeUndefined();
        expect(notification.destroyedOn).toBeUndefined();
      })
    );//test info


    it('call alert bare',
      inject([NotificationsService], (service: NotificationsService) => {
        let notificationEvent: NotificationEvent = null;
        service.getChangeEmitter().subscribe(item => notificationEvent = item);

        let notification: Notification = service.bare('Window title', 'Content message');

        expect(notificationEvent.command).toBe('set');

        expect(notification.id !== undefined).toBeTruthy();
        expect(notification.type).toBe('bare');
        expect(notification.icon).toBe('bare');

        expect(notification.title).toBe('Window title');
        expect(notification.content).toBe('Content message');
        expect(notification.override).toBeUndefined();
        expect(notification.html).toBeUndefined();
        expect(notification.state).toBeUndefined();
        expect(notification.createdOn).toBeUndefined();
        expect(notification.destroyedOn).toBeUndefined();
      })
    );//test bare


    it('call alert create',
      inject([NotificationsService], (service: NotificationsService) => {
        let notificationEvent: NotificationEvent = null;
        service.getChangeEmitter().subscribe(item => notificationEvent = item);

        let notification: Notification = service.create('Window title', 'Content message', 'create');

        expect(notificationEvent.command).toBe('set');

        expect(notification.id !== undefined).toBeTruthy();
        expect(notification.type).toBe('create');
        expect(notification.icon).toBe('bare');

        expect(notification.title).toBe('Window title');
        expect(notification.content).toBe('Content message');
        expect(notification.override).toBeUndefined();
        expect(notification.html).toBeUndefined();
        expect(notification.state).toBeUndefined();
        expect(notification.createdOn).toBeUndefined();
        expect(notification.destroyedOn).toBeUndefined();
      })
    );//test create


    it('call alert html',
      inject([NotificationsService], (service: NotificationsService) => {
        let notificationEvent: NotificationEvent = null;
        service.getChangeEmitter().subscribe(item => notificationEvent = item);

        let notification: Notification = service.html('<B>Window title</B>', 'success');

        expect(notificationEvent.command).toBe('set');

        expect(notification.id !== undefined).toBeTruthy();
        expect(notification.type).toBe('success');
        expect(notification.icon).toBe('bare');

        expect(notification.title).toBeNull();
        expect(notification.content).toBeNull();
        expect(notification.override).toBeUndefined();
        expect(notification.html).toBe('<B>Window title</B>');
        expect(notification.state).toBeUndefined();
        expect(notification.createdOn).toBeUndefined();
        expect(notification.destroyedOn).toBeUndefined();
      })
    );

    it('call remove to emit cleanAll event',
      inject([NotificationsService], (service: NotificationsService) => {
        let notificationEvent: NotificationEvent = null;
        service.getChangeEmitter().subscribe(item => notificationEvent = item);

        service.remove();

        expect(notificationEvent.command).toBe('cleanAll');
      })
    );

    it('call remove with id to emit clean event',
      inject([NotificationsService], (service: NotificationsService) => {
        let notificationEvent: NotificationEvent = null;
        service.getChangeEmitter().subscribe(item => notificationEvent = item);

        service.remove('1');

        expect(notificationEvent.command).toBe('clean');
        expect(notificationEvent.id).toBe('1');
      })
    );

  });





```

**Comment by flauc** [comment]
Do we really need angular cli to run the tests? I think it's a bit of an overkill.

**Comment by netstart** [comment]
OK, but implicit any type is an bad practice in TypeScript.
I beleave that JavaScript it´s ok, but in TypeScript is an badsmell.

I make this object to remove implicit any type (sorry for my bad english, is not my first language)

**Pull request closed without merging**
