### PR TITLE
Override icons in general

### PR DESCRIPTION
**Pull request by mkollers**
Also depending on #165 - this allows us to override the default icons by setting them inside of the service, or adding them to the [options]-object.

### CODE REVIEW

**Comment by flauc** [comment]
awesome 👍

**Comment by mkollers** [comment]
Great lib, thanks for your fast response!

**Comment by mkollers** [comment]
How long does it take to get a new npm release? :-)

**Comment by flauc** [comment]
Meh, usually short I forgot about this updates.

**Comment by flauc** [comment]
I just released the new version, sorry about that.

**Pull request merged**
